// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuKAU2wC8baIEEW-PEgqzbEDkYnhgCyM8',
    appId: '1:807285695:web:c4302882513fecc938670a',
    messagingSenderId: '807285695',
    projectId: 'in-cw16',
    authDomain: 'in-cw16.firebaseapp.com',
    storageBucket: 'in-cw16.firebasestorage.app',
    measurementId: 'G-W6X2B915FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-UhgQxTCOxxAtys9eP5rXO7BSqE4-_1M',
    appId: '1:807285695:android:4d6d964e762d815238670a',
    messagingSenderId: '807285695',
    projectId: 'in-cw16',
    storageBucket: 'in-cw16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaYsw5aNehojYPG3V92wMGAM4ozi9wW8s',
    appId: '1:807285695:ios:34eb7c8e8ea9b61438670a',
    messagingSenderId: '807285695',
    projectId: 'in-cw16',
    storageBucket: 'in-cw16.firebasestorage.app',
    iosBundleId: 'com.example.incw16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaYsw5aNehojYPG3V92wMGAM4ozi9wW8s',
    appId: '1:807285695:ios:34eb7c8e8ea9b61438670a',
    messagingSenderId: '807285695',
    projectId: 'in-cw16',
    storageBucket: 'in-cw16.firebasestorage.app',
    iosBundleId: 'com.example.incw16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuKAU2wC8baIEEW-PEgqzbEDkYnhgCyM8',
    appId: '1:807285695:web:677ef336616d944138670a',
    messagingSenderId: '807285695',
    projectId: 'in-cw16',
    authDomain: 'in-cw16.firebaseapp.com',
    storageBucket: 'in-cw16.firebasestorage.app',
    measurementId: 'G-PD3BS43L0F',
  );
}
